{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "",
      "DisplayName": ""
    },
    "ClosedComment": "2.2 release",
    "ClosedDate": "2015-04-09T12:18:37.41-07:00",
    "CommentCount": 0,
    "Custom": null,
    "Description": "Hi,\nI am using CRM 2015.\nWhen I call XrmServiceToolkit.Soap.Update it never throws/returns error.\n\n#Sinchronous call\n```\nvar result = XrmServiceToolkit.Soap.Update(crmActivity);\n```\nresult is always an empty string, even if an error occurred.\n#Asynchronous call\n```\ntry\n{\n    XrmServiceToolkit.Soap.Update(crmEntity, endUpdateHandler);\n}\ncatch (e)\n{\n    // handle error\n}\n```\nAn error is never thrown, even if the call is malformed.\n\nThank you,\nGabriele",
    "LastUpdatedDate": "2015-04-09T12:18:37.41-07:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Unassigned",
      "Severity": 0,
      "Id": 0
    },
    "ProjectName": "xrmservicetoolkit",
    "ReportedDate": "2015-01-23T06:06:10.55-08:00",
    "Status": {
      "Name": "Closed",
      "Id": 4
    },
    "ReasonClosed": {
      "Name": "Fixed"
    },
    "Summary": "XrmServiceToolkit.Soap.Update does not show errors",
    "Type": {
      "Name": "Unassigned",
      "Id": 5
    },
    "VoteCount": 2,
    "Id": 1778
  },
  "FileAttachments": [],
  "Comments": [
    {
      "Message": "I am also seeing this issue with the 'Create' method",
      "PostedDate": "2015-02-24T17:03:55.437-08:00",
      "Id": -2147483648
    },
    {
      "Message": "Hi,\r\n\r\nError handling is already being discussed in a different Thread (http://xrmservicetoolkit.codeplex.com/workitem/1749) and according to Jamie going to be fixed in the next release.\r\n\r\njohnny\n",
      "PostedDate": "2015-02-24T23:08:03.67-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2015-04-09T12:18:37.41-07:00",
      "Id": -2147483648
    }
  ]
}